### PR TITLE
czech language

### PR DESCRIPTION
**Pull request by Kaul1k**
Hi, I translate it to czech language and add something like your ru/en version but cz/en. Please, can you add it to shieldy?
Thank you.

### CODE REVIEW

**Comment by backmeupplz** [comment]
Thank you a lot! Is there a funny name for such czen translation, like `Czechlish`?

**Comment by backmeupplz** [comment]
I used `Czechlish`, hope it's ok

**Comment by Kaul1k** [comment]
Sorry but I must done something wrong :-\ it doesn't work. I'm looking for the solution.

**Comment by backmeupplz** [comment]
@Kaul1k can you specify what doesn't work, please? It looks like it works when I select the language with `/language` command. Please, make sure to set up the bot in group chat, not in private messages.

**Comment by Kaul1k** [comment]
Sorry It works now. It didn't work before you repair the address on czen language.

**Pull request merged**
